#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Usage: $0 <emmc_dev>"
    exit 1
fi

shopt -s extglob  # For extended globbing of /boot/*.{txt,ini,...}

emmc_dev=$1

function msg() {
    echo " * $1"
}

root_dev=$(cat /proc/cmdline | grep -oE 'root=[/a-z0-9]+' | cut -d '=' -f 2)
if [[ "${root_dev}" =~ ^([/a-z0-9]+)(p[0-9])$ ]]; then  # e.g. /dev/mmcblk0p2
    disk_dev=${BASH_REMATCH[1]}
    disk_dev_prefix=${disk_dev}p
    boot_dev=${disk_dev}p1
    data_dev=${disk_dev}p3
elif [[ "${root_dev}" =~ ^([/a-z0-9]+)([0-9])$ ]]; then  # e.g. /dev/sdc2
    disk_dev=${BASH_REMATCH[1]}
    disk_dev_prefix=${disk_dev}
    boot_dev=${disk_dev}1
    data_dev=${disk_dev}3
else
    msg "Unknown root device ${root_dev}"
    exit 1
fi

msg "SD card device is ${disk_dev}"

root_info=$(fdisk -l -o device,start,end,size ${disk_dev} | grep "${root_dev}")
root_info=(${root_info})

root_end_sector=${root_info[2]}
total_size=$(((root_end_sector + 1) * 512 / 10485760))  # x 10MB

msg "Unmounting all EMMC partitions"
umount ${emmc_dev}* &>/dev/null
partx -d ${emmc_dev} &>/dev/null

msg "Copying ${total_size}0MB from ${disk_dev} to ${emmc_dev}"
dd if=${disk_dev} of=${emmc_dev} bs=10M count=${total_size} status=none
sync
partx -a ${emmc_dev} &>/dev/null

msg "Removing data partition from EMMC"
fdisk >/dev/null ${emmc_dev} <<END
d
3
w
END
sync

msg "Mounting ${emmc_dev}p1 boot partition"
mkdir -p /data/.emmc_boot
mount ${emmc_dev}p1 /data/.emmc_boot
cd /data/.emmc_boot

msg "Ajusting EMMC root device"
sed -i "s,${disk_dev},${emmc_dev},g" *.@(txt|ini|conf)

msg "Cleaning up"
cd - >/dev/null
umount /data/.emmc_boot
rmdir /data/.emmc_boot

msg "Done!"
